"""empty message

Revision ID: 216aa645ada2
Revises: 569ea1df8eb4
Create Date: 2015-06-27 22:16:58.708959

"""

# revision identifiers, used by Alembic.
revision = '216aa645ada2'
down_revision = '569ea1df8eb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
