"""empty message

Revision ID: 3af6121697a3
Revises: 3023a4721fe4
Create Date: 2015-06-27 15:53:28.690786

"""

# revision identifiers, used by Alembic.
revision = '3af6121697a3'
down_revision = '3023a4721fe4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
