"""empty message

Revision ID: 526bb585c724
Revises: 3af6121697a3
Create Date: 2015-06-27 16:22:00.597558

"""

# revision identifiers, used by Alembic.
revision = '526bb585c724'
down_revision = '3af6121697a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'roles')
    op.drop_table(u'users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'users',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'username', sa.VARCHAR(length=64), nullable=True),
    sa.Column(u'role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'roles',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    ### end Alembic commands ###
