"""empty message

Revision ID: 5828409f86e1
Revises: 526bb585c724
Create Date: 2015-06-27 16:34:23.237468

"""

# revision identifiers, used by Alembic.
revision = '5828409f86e1'
down_revision = '526bb585c724'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
